browser = chrome
url = https://automationexercise.com/
implicitWait = 10
name = john

// signup info

signUpEmail = johnxyz@gmail.com
password = 12345678
day = 12
month = May
year = 2000
fName = John
lName = Cena
company = ABC
address1 = CP
address2 = Dwarka
state = Delhi
city = Delhi
zipcode = 123456
mobile = 123456790


